apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: cloudsqlproxy
    app.kubernetes.io/instance: cloudsqlproxy
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/component: cloudsqlproxy
    app.kubernetes.io/part-of: cloudsqlproxy
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app.kubernetes.io/name: cloudsqlproxy
    app.kubernetes.io/instance: cloudsqlproxy
    serving: "true"
